flags = [
        '-Wall',
        '-Wextra',
        '-Werror',
        '-fexceptions',
        '-DNDEBUG', 
        '-std=c++11', 
        '-x',
        'c++',
        '-isystem',
        '/usr/include',
        '-isystem',
        '/usr/include/x86_64-linux-gnu/c++/',
        '-isystem',
        '/usr/include/c++/5.4.0',
        '-isystem',
        './header',
        ]
